FROM arm32v7/python:3.7-slim-buster

ADD . /

RUN apt-get -q update && \
	apt-get -qy install \ 
	libatlas-base-dev \
	libgomp1

RUN pip install --no-cache-dir "pandas==0.25.3"  -i https://www.piwheels.hostedpi.com/simple/
RUN pip install --no-cache-dir "scikit-learn==0.22" -i https://www.piwheels.hostedpi.com/simple/
RUN pip install --no-cache-dir "numpy==1.17.4"  -i https://www.piwheels.hostedpi.com/simple/
#RUN apt-get install -y python3-pandas

CMD ["python", "./try1.py" ]
