version : "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
  mongo-express:
     image: mongo-express
     restart: always
     ports:
       - 8081:8081
     container_name: mongoexpress